### ISSUE TITLE
Found Bug when using payment system

### ISSUE THREAD

**Issue by dat911zz** [nhamngo29/WebsiteBanHang#2]
![image](https://github.com/nhamngo29/WebsiteBanHang/assets/74701328/3d3a62fd-ae6f-44e5-a8b9-e9b0361a61e9)

**Comment by nhamngo29** [comment]
Web vẫn đang trong quá trình phát triển :vvv

**Comment by dat911zz** [comment]
> Web vẫn đang trong quá trình phát triển :vvv

dc đấy bro =)))
